; Auto-generated. Do not edit!


(cl:in-package robotarminterface-msg)


;//! \htmlinclude ServoGoal.msg.html

(cl:defclass <ServoGoal> (roslisp-msg-protocol:ros-message)
  ((pulsewidth
    :reader pulsewidth
    :initarg :pulsewidth
    :type cl:fixnum
    :initform 0))
)

(cl:defclass ServoGoal (<ServoGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ServoGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ServoGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robotarminterface-msg:<ServoGoal> is deprecated: use robotarminterface-msg:ServoGoal instead.")))

(cl:ensure-generic-function 'pulsewidth-val :lambda-list '(m))
(cl:defmethod pulsewidth-val ((m <ServoGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robotarminterface-msg:pulsewidth-val is deprecated.  Use robotarminterface-msg:pulsewidth instead.")
  (pulsewidth m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ServoGoal>) ostream)
  "Serializes a message object of type '<ServoGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'pulsewidth)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'pulsewidth)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ServoGoal>) istream)
  "Deserializes a message object of type '<ServoGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'pulsewidth)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'pulsewidth)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ServoGoal>)))
  "Returns string type for a message object of type '<ServoGoal>"
  "robotarminterface/ServoGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ServoGoal)))
  "Returns string type for a message object of type 'ServoGoal"
  "robotarminterface/ServoGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ServoGoal>)))
  "Returns md5sum for a message object of type '<ServoGoal>"
  "1930e8bfd98a1ac05b9f850d8f71dbbc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ServoGoal)))
  "Returns md5sum for a message object of type 'ServoGoal"
  "1930e8bfd98a1ac05b9f850d8f71dbbc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ServoGoal>)))
  "Returns full string definition for message of type '<ServoGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%uint16 pulsewidth~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ServoGoal)))
  "Returns full string definition for message of type 'ServoGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%uint16 pulsewidth~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ServoGoal>))
  (cl:+ 0
     2
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ServoGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ServoGoal
    (cl:cons ':pulsewidth (pulsewidth msg))
))
