; Auto-generated. Do not edit!


(cl:in-package robotarminterface-msg)


;//! \htmlinclude ServoFeedback.msg.html

(cl:defclass <ServoFeedback> (roslisp-msg-protocol:ros-message)
  ((pulsewidth
    :reader pulsewidth
    :initarg :pulsewidth
    :type cl:fixnum
    :initform 0))
)

(cl:defclass ServoFeedback (<ServoFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ServoFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ServoFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robotarminterface-msg:<ServoFeedback> is deprecated: use robotarminterface-msg:ServoFeedback instead.")))

(cl:ensure-generic-function 'pulsewidth-val :lambda-list '(m))
(cl:defmethod pulsewidth-val ((m <ServoFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robotarminterface-msg:pulsewidth-val is deprecated.  Use robotarminterface-msg:pulsewidth instead.")
  (pulsewidth m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ServoFeedback>) ostream)
  "Serializes a message object of type '<ServoFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'pulsewidth)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'pulsewidth)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ServoFeedback>) istream)
  "Deserializes a message object of type '<ServoFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'pulsewidth)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'pulsewidth)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ServoFeedback>)))
  "Returns string type for a message object of type '<ServoFeedback>"
  "robotarminterface/ServoFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ServoFeedback)))
  "Returns string type for a message object of type 'ServoFeedback"
  "robotarminterface/ServoFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ServoFeedback>)))
  "Returns md5sum for a message object of type '<ServoFeedback>"
  "1930e8bfd98a1ac05b9f850d8f71dbbc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ServoFeedback)))
  "Returns md5sum for a message object of type 'ServoFeedback"
  "1930e8bfd98a1ac05b9f850d8f71dbbc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ServoFeedback>)))
  "Returns full string definition for message of type '<ServoFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%uint16 pulsewidth~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ServoFeedback)))
  "Returns full string definition for message of type 'ServoFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%uint16 pulsewidth~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ServoFeedback>))
  (cl:+ 0
     2
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ServoFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ServoFeedback
    (cl:cons ':pulsewidth (pulsewidth msg))
))
