// Generated by gencpp from file robotarminterface/allServo.msg
// DO NOT EDIT!


#ifndef ROBOTARMINTERFACE_MESSAGE_ALLSERVO_H
#define ROBOTARMINTERFACE_MESSAGE_ALLSERVO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robotarminterface/servoPosition.h>
#include <robotarminterface/servoPosition.h>
#include <robotarminterface/servoPosition.h>
#include <robotarminterface/servoPosition.h>
#include <robotarminterface/servoPosition.h>
#include <robotarminterface/servoPosition.h>

namespace robotarminterface
{
template <class ContainerAllocator>
struct allServo_
{
  typedef allServo_<ContainerAllocator> Type;

  allServo_()
    : Servo0()
    , Servo1()
    , Servo2()
    , Servo3()
    , Servo4()
    , Servo5()
    , time(0)  {
    }
  allServo_(const ContainerAllocator& _alloc)
    : Servo0(_alloc)
    , Servo1(_alloc)
    , Servo2(_alloc)
    , Servo3(_alloc)
    , Servo4(_alloc)
    , Servo5(_alloc)
    , time(0)  {
  (void)_alloc;
    }



   typedef  ::robotarminterface::servoPosition_<ContainerAllocator>  _Servo0_type;
  _Servo0_type Servo0;

   typedef  ::robotarminterface::servoPosition_<ContainerAllocator>  _Servo1_type;
  _Servo1_type Servo1;

   typedef  ::robotarminterface::servoPosition_<ContainerAllocator>  _Servo2_type;
  _Servo2_type Servo2;

   typedef  ::robotarminterface::servoPosition_<ContainerAllocator>  _Servo3_type;
  _Servo3_type Servo3;

   typedef  ::robotarminterface::servoPosition_<ContainerAllocator>  _Servo4_type;
  _Servo4_type Servo4;

   typedef  ::robotarminterface::servoPosition_<ContainerAllocator>  _Servo5_type;
  _Servo5_type Servo5;

   typedef uint32_t _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::robotarminterface::allServo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotarminterface::allServo_<ContainerAllocator> const> ConstPtr;

}; // struct allServo_

typedef ::robotarminterface::allServo_<std::allocator<void> > allServo;

typedef boost::shared_ptr< ::robotarminterface::allServo > allServoPtr;
typedef boost::shared_ptr< ::robotarminterface::allServo const> allServoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotarminterface::allServo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotarminterface::allServo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotarminterface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'robotarminterface': ['/home/owner/git/AL5D-Interface/ros/catkin_ws/src/robotarminterface/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotarminterface::allServo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotarminterface::allServo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarminterface::allServo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarminterface::allServo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarminterface::allServo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarminterface::allServo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotarminterface::allServo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "121b57178428382073f8fc86c837ef06";
  }

  static const char* value(const ::robotarminterface::allServo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x121b571784283820ULL;
  static const uint64_t static_value2 = 0x73f8fc86c837ef06ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotarminterface::allServo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotarminterface/allServo";
  }

  static const char* value(const ::robotarminterface::allServo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotarminterface::allServo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servoPosition Servo0\n\
servoPosition Servo1\n\
servoPosition Servo2\n\
servoPosition Servo3\n\
servoPosition Servo4\n\
servoPosition Servo5\n\
uint32 time\n\
================================================================================\n\
MSG: robotarminterface/servoPosition\n\
uint32 servoId\n\
uint32 position\n\
";
  }

  static const char* value(const ::robotarminterface::allServo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotarminterface::allServo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Servo0);
      stream.next(m.Servo1);
      stream.next(m.Servo2);
      stream.next(m.Servo3);
      stream.next(m.Servo4);
      stream.next(m.Servo5);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct allServo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotarminterface::allServo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotarminterface::allServo_<ContainerAllocator>& v)
  {
    s << indent << "Servo0: ";
    s << std::endl;
    Printer< ::robotarminterface::servoPosition_<ContainerAllocator> >::stream(s, indent + "  ", v.Servo0);
    s << indent << "Servo1: ";
    s << std::endl;
    Printer< ::robotarminterface::servoPosition_<ContainerAllocator> >::stream(s, indent + "  ", v.Servo1);
    s << indent << "Servo2: ";
    s << std::endl;
    Printer< ::robotarminterface::servoPosition_<ContainerAllocator> >::stream(s, indent + "  ", v.Servo2);
    s << indent << "Servo3: ";
    s << std::endl;
    Printer< ::robotarminterface::servoPosition_<ContainerAllocator> >::stream(s, indent + "  ", v.Servo3);
    s << indent << "Servo4: ";
    s << std::endl;
    Printer< ::robotarminterface::servoPosition_<ContainerAllocator> >::stream(s, indent + "  ", v.Servo4);
    s << indent << "Servo5: ";
    s << std::endl;
    Printer< ::robotarminterface::servoPosition_<ContainerAllocator> >::stream(s, indent + "  ", v.Servo5);
    s << indent << "time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTARMINTERFACE_MESSAGE_ALLSERVO_H
