// Generated by gencpp from file robotarminterface/ServoGoal.msg
// DO NOT EDIT!


#ifndef ROBOTARMINTERFACE_MESSAGE_SERVOGOAL_H
#define ROBOTARMINTERFACE_MESSAGE_SERVOGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotarminterface
{
template <class ContainerAllocator>
struct ServoGoal_
{
  typedef ServoGoal_<ContainerAllocator> Type;

  ServoGoal_()
    : pulsewidth(0)  {
    }
  ServoGoal_(const ContainerAllocator& _alloc)
    : pulsewidth(0)  {
  (void)_alloc;
    }



   typedef uint16_t _pulsewidth_type;
  _pulsewidth_type pulsewidth;





  typedef boost::shared_ptr< ::robotarminterface::ServoGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotarminterface::ServoGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ServoGoal_

typedef ::robotarminterface::ServoGoal_<std::allocator<void> > ServoGoal;

typedef boost::shared_ptr< ::robotarminterface::ServoGoal > ServoGoalPtr;
typedef boost::shared_ptr< ::robotarminterface::ServoGoal const> ServoGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotarminterface::ServoGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotarminterface::ServoGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotarminterface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'robotarminterface': ['/home/owner/git/AL5D-Interface/ros/catkin_ws/devel/share/robotarminterface/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotarminterface::ServoGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotarminterface::ServoGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarminterface::ServoGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarminterface::ServoGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarminterface::ServoGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarminterface::ServoGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotarminterface::ServoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1930e8bfd98a1ac05b9f850d8f71dbbc";
  }

  static const char* value(const ::robotarminterface::ServoGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1930e8bfd98a1ac0ULL;
  static const uint64_t static_value2 = 0x5b9f850d8f71dbbcULL;
};

template<class ContainerAllocator>
struct DataType< ::robotarminterface::ServoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotarminterface/ServoGoal";
  }

  static const char* value(const ::robotarminterface::ServoGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotarminterface::ServoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
uint16 pulsewidth\n\
";
  }

  static const char* value(const ::robotarminterface::ServoGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotarminterface::ServoGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pulsewidth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotarminterface::ServoGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotarminterface::ServoGoal_<ContainerAllocator>& v)
  {
    s << indent << "pulsewidth: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.pulsewidth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTARMINTERFACE_MESSAGE_SERVOGOAL_H
